export const IPC_CHANNELS = {
  explainRegion: 'tutor:explain-region',
  explainProgress: 'tutor:explain-progress',
  answerDelta: 'tutor:answer-delta',
  askFollowUp: 'tutor:ask-follow-up',
  cancelRequest: 'tutor:cancel-request',
  endQuestionSession: 'tutor:end-question-session',
  getApiDefaults: 'tutor:get-api-defaults',
  listApiProviders: 'tutor:list-api-providers',
  getOverlayBounds: 'tutor:get-overlay-bounds',
  listModels: 'tutor:list-models',
  checkForUpdates: 'tutor:check-for-updates',
  installUpdate: 'tutor:install-update',
  updateStatus: 'tutor:update-status',
  getLatestAnnouncement: 'tutor:get-latest-announcement',
  connectAnnouncements: 'tutor:connect-announcements',
  announcement: 'tutor:announcement',
  getAppVersion: 'tutor:get-app-version',
  setDebugMode: 'tutor:set-debug-mode',
  setMousePassthrough: 'tutor:set-mouse-passthrough',
  setCaptureUiVisible: 'tutor:set-capture-ui-visible'
} as const;
